# Python Data Analysis Project

## The Weather Dataset

In [1]:
import pandas as pd

In [73]:
import numpy as np

In [2]:
data = pd.read_csv("/Users/archanaqueen/Desktop/i18n/Python Projects/weather.csv")

In [3]:
data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [4]:
# To explore the data

In [5]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [7]:
data.shape # gives total number of rows and columns

(366, 22)

In [8]:
data.index # range of the dataframe

RangeIndex(start=0, stop=366, step=1)

In [9]:
data.columns # to know the column names

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [10]:
data.dtypes # It shows datatype of each column

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [11]:
data['MinTemp'].unique() # shows all unique values in each column

array([ 8. , 14. , 13.7, 13.3,  7.6,  6.2,  6.1,  8.3,  8.8,  8.4,  9.1,
        8.5, 10.1, 12.1, 12.4, 13.8, 11.7, 15.6, 15.3, 16.4, 12.8, 12. ,
       15.4, 12.9, 15.1, 13.6, 11.6, 16.6, 14.5, 16.3, 17.2, 16.5, 15. ,
       14.9, 11.8,  9.6,  8.9, 15.5, 10.8,  7.5, 12.6, 14.8, 19.9,  9.2,
       11.3,  9.8, 14.3, 14.4, 15.9, 16.7, 17.5, 14.7, 20.9, 17. , 16. ,
       17.9, 15.2, 10. ,  9.9, 10.3, 12.7, 13.2, 18. , 17.6, 17.1, 18.2,
       16.8, 10.4,  8.6, 11.2, 11.4, 11.5, 13. ,  7.7,  4.4,  7.4,  9.5,
       12.5, 13.9, 12.3, 13.1,  7.1,  4.2,  3.5,  5.3,  7. ,  0.4,  3.2,
        5.9,  8.1,  6.9,  5.6,  7.2,  5.4,  6.3,  7.9,  2.4,  2.5,  5. ,
        3.8,  4.3, -2.1, -1.8,  2.1,  0.5, -0.9, -0.2,  0.1,  1.5,  9.4,
        1.3,  2.2, -0.4,  4.5, -2.7,  0.3,  1.2, -0.3,  4.7,  4.9,  1.4,
       -0.1,  0.6,  4.6, 10.6,  7.8, 10.2,  7.3,  8.7,  1. ,  6.4,  4. ,
        0.9,  0.8, -1.5,  6.6, -1.6, -3.1, -0.6,  3. ,  2.9, -1.3,  1.8,
       -2.6,  2.7, -1.7, -1.1,  2.3, -2.2, -3.5, -1. , -2. , -2.3, -2.8,
       -1.9,  4.8,  3.1, -2.9,  3.7, -3.4, -5.3,  0. , -3.7, -3.3,  4.1,
        5.8,  0.2, -2.5, -0.5,  9. ,  3.9,  0.7,  1.1,  5.1,  6.5,  8.2,
        6.7, 11.9,  3.4,  3.3])

In [22]:
len(data['MinTemp'].unique())

180

In [14]:
# nunique shows total no.of values in each column.It can be applied both in single column or whole dataframe

In [12]:
data.nunique()

MinTemp          180
MaxTemp          187
Rainfall          47
Evaporation       55
Sunshine         114
WindGustDir       16
WindGustSpeed     35
WindDir9am        16
WindDir3pm        16
WindSpeed9am      22
WindSpeed3pm      26
Humidity9am       60
Humidity3pm       74
Pressure9am      190
Pressure3pm      193
Cloud9am           9
Cloud3pm           9
Temp9am          178
Temp3pm          200
RainToday          2
RISK_MM           47
RainTomorrow       2
dtype: int64

In [23]:
data['WindGustDir'].nunique()

16

In [21]:
data['MinTemp'].nunique()

180

In [15]:
# count shows total number of non-null values in each column or entire dataframe

In [19]:
data.count()

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

In [18]:
data['RainToday'].count()

366

In [20]:
# value_counts shows all their unique values with their count. It can be applied on a single column only.

In [26]:
data['RainToday'].value_counts()

No     300
Yes     66
Name: RainToday, dtype: int64

In [27]:
data.info() # basic info of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        366 non-null    float64
 1   MaxTemp        366 non-null    float64
 2   Rainfall       366 non-null    float64
 3   Evaporation    366 non-null    float64
 4   Sunshine       363 non-null    float64
 5   WindGustDir    363 non-null    object
 6   WindGustSpeed  364 non-null    float64
 7   WindDir9am     335 non-null    object
 8   WindDir3pm     365 non-null    object
 9   WindSpeed9am   359 non-null    float64
 10  WindSpeed3pm   366 non-null    int64
 11  Humidity9am    366 non-null    int64
 12  Humidity3pm    366 non-null    int64
 13  Pressure9am    366 non-null    float64
 14  Pressure3pm    366 non-null    float64
 15  Cloud9am       366 non-null    int64
 16  Cloud3pm       366 non-null    int64
 17  Temp9am        366 non-null    float64
 18  Temp3pm        366 non-null    float64
 19  RainToday      366 non-null    object
 20  RISK_MM        366 non-null    float64
 21  RainTomorrow   366 non-null    object
dtypes: float64(12), int64(5), object(5)
memory usage: 63.0+ KB

In [28]:
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

## Queries and Answers

In [29]:
data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# 1) Find all the unique "WindGustSpeed" values in the data

In [31]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [32]:
data.nunique() # it shows for all. here windgustspeed has 35 values unique

MinTemp          180
MaxTemp          187
Rainfall          47
Evaporation       55
Sunshine         114
WindGustDir       16
WindGustSpeed     35
WindDir9am        16
WindDir3pm        16
WindSpeed9am      22
WindSpeed3pm      26
Humidity9am       60
Humidity3pm       74
Pressure9am      190
Pressure3pm      193
Cloud9am           9
Cloud3pm           9
Temp9am          178
Temp3pm          200
RainToday          2
RISK_MM           47
RainTomorrow       2
dtype: int64

In [34]:
data["WindGustSpeed"].nunique()

35

In [35]:
# Answer

In [36]:
data["WindGustSpeed"].unique()

array([30., 39., 85., 54., 50., 44., 43., 41., 48., 31., 46., 52., 33.,
       59., 26., 28., 35., 22., 76., 65., 57., 69., 61., 24., 83., 63.,
       17., 20., nan, 15., 13., 70., 78., 67., 98., 80.])

In [37]:
# including nan means it shows 36

# 2) Find the number of times when there is a rain tomorrow is 'Yes'?

In [38]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [39]:
# value_counts

In [43]:
data["RainTomorrow"]

0      Yes
1      Yes
2      Yes
3      Yes
4       No
      ...
361     No
362     No
363     No
364     No
365     No
Name: RainTomorrow, Length: 366, dtype: object

In [45]:
data["RainTomorrow"].value_counts()

No     300
Yes     66
Name: RainTomorrow, dtype: int64

In [46]:
# Filtering

In [47]:
data["RainTomorrow"] == "Yes"

0       True
1       True
2       True
3       True
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: RainTomorrow, Length: 366, dtype: bool

In [48]:
data[data["RainTomorrow"] == "Yes"]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1012.1,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1016.3,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1009.5,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1020.9,1016.0,4,7,16.3,23.2,No,13.2,Yes

In [49]:
# groupby

In [50]:
data.groupby("RainTomorrow").get_group("Yes")

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1012.1,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1016.3,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1009.5,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1020.9,1016.0,4,7,16.3,23.2,No,13.2,Yes

# 3) Find the number of times when the "cloud9am at 7"

In [51]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [52]:
# value_counts

In [54]:
data["Cloud9am"]

0      7
1      5
2      8
3      2
4      7
      ..
361    1
362    0
363    3
364    6
365    1
Name: Cloud9am, Length: 366, dtype: int64

In [55]:
data["Cloud9am"].value_counts()

1    116
7     86
8     40
0     33
6     25
5     23
2     17
3     17
4      9
Name: Cloud9am, dtype: int64

In [56]:
# Filtering

In [58]:
data["Cloud9am"] == 7

0       True
1      False
2      False
3      False
4       True
       ...
361    False
362    False
363    False
364    False
365    False
Name: Cloud9am, Length: 366, dtype: bool

In [59]:
data[data["Cloud9am"] == 7]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,0.7,14.1,0.0,5.6,9.0,ENE,20.0,SSW,NNW,6.0,...,43,1026.7,1022.1,7,1,7.4,13.7,No,0.0,No
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No
349,9.2,19.6,0.6,3.4,10.4,ENE,31.0,SSE,NNW,4.0,...,42,1022.3,1019.7,7,4,11.6,18.4,No,0.0,No
355,9.0,20.6,0.0,9.0,6.2,ENE,39.0,S,SW,11.0,...,28,1022.3,1018.6,7,5,11.4,18.5,No,0.8,No

In [60]:
# groupby

In [61]:
data.groupby("Cloud9am").get_group(7)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,0.7,14.1,0.0,5.6,9.0,ENE,20.0,SSW,NNW,6.0,...,43,1026.7,1022.1,7,1,7.4,13.7,No,0.0,No
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No
349,9.2,19.6,0.6,3.4,10.4,ENE,31.0,SSE,NNW,4.0,...,42,1022.3,1019.7,7,4,11.6,18.4,No,0.0,No
355,9.0,20.6,0.0,9.0,6.2,ENE,39.0,S,SW,11.0,...,28,1022.3,1018.6,7,5,11.4,18.5,No,0.8,No

# 4) Find out all the Null values in the data

In [62]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [63]:
data.isnull()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
362,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
363,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
364,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
365,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [64]:
# To avoid this as in bollean form. We use sum()

In [65]:
data.isnull().sum()

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

In [66]:
data.notnull().sum() # it shows not null values

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

In [67]:
# 5) Rename the column name "RainToday" of the dataframe to "WeatherConditionToday"

In [68]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [69]:
data.rename(columns = {"RainToday" : "WeatherConditionToday"})

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [70]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [71]:
data.rename(columns = {"RainToday" : "WeatherConditionToday"}, inplace=True)

In [72]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

# 6) What is the mean of the "Evaporation"?

In [74]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [75]:
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [76]:
data["Evaporation"].mean()

4.521857923497269

In [77]:
# Manual calculation

In [81]:
sum = data["Evaporation"].sum()

In [82]:
sum

1655.0

In [79]:
length = len(data["Evaporation"])

In [80]:
length

366

In [83]:
mean = sum / length

In [84]:
mean

4.521857923497268

# 7) What is the Standard Deviation of "Pressure9am" in this data?

In [85]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [86]:
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [87]:
data["Pressure9am"]

0      1019.7
1      1012.4
2      1009.5
3      1005.5
4      1018.3
        ...
361    1016.1
362    1020.0
363    1024.0
364    1021.0
365    1009.6
Name: Pressure9am, Length: 366, dtype: float64

In [88]:
data["Pressure9am"].std()

6.686211582894859

In [89]:
# Manual calculation

std = sqrt((x - x^)^2 / n)

In [90]:
x = data["Pressure9am"]

In [91]:
x

0      1019.7
1      1012.4
2      1009.5
3      1005.5
4      1018.3
        ...
361    1016.1
362    1020.0
363    1024.0
364    1021.0
365    1009.6
Name: Pressure9am, Length: 366, dtype: float64

In [92]:
x_bar = data["Pressure9am"].mean()

In [93]:
x_bar

1019.7090163934431

In [95]:
sum = data["Pressure9am"].sum()

In [96]:
sum

373213.50000000006

In [97]:
length = len(data["Pressure9am"])

In [98]:
length

366

In [99]:
mean = sum / length

In [100]:
mean

1019.7090163934428

In [104]:
data["Pressure9am"].var()

44.70542533123737

In [105]:
np.sqrt(data["Pressure9am"].var())

6.686211582894859

In [106]:
data["Pressure9am"].std()

6.686211582894859

# 8) What is the standard deviation of "Sunshine"?

In [107]:
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [108]:
data["Sunshine"].std()

3.4815171624059222

# 9) Find all the instances when WindGustDir is "NW"?

In [109]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [110]:
data["WindGustDir"]

0       NW
1      ENE
2       NW
3       NW
4      SSE
      ...
361    NNW
362      N
363    ESE
364     NW
365     NW
Name: WindGustDir, Length: 366, dtype: object

In [114]:
# value_counts

In [115]:
data["WindGustDir"].value_counts()

NW     73
NNW    44
E      37
WNW    35
ENE    30
ESE    23
S      22
N      21
W      20
NE     16
SSE    12
SE     12
NNE     8
SSW     5
SW      3
WSW     2
Name: WindGustDir, dtype: int64

In [116]:
# Filtering

In [117]:
data["WindGustDir"] == "NW"

0       True
1      False
2       True
3       True
4      False
       ...
361    False
362    False
363    False
364     True
365     True
Name: WindGustDir, Length: 366, dtype: bool

In [118]:
data[data["WindGustDir"] == "NW"]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
13,12.1,30.9,0.0,6.2,12.4,NW,44.0,WNW,W,7.0,...,20,1017.3,1013.1,1,4,19.7,30.7,No,0.0,No
14,10.1,31.2,0.0,8.8,13.1,NW,41.0,S,W,6.0,...,16,1018.2,1013.7,0,1,18.7,30.4,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,6.7,24.7,0.0,5.4,8.6,NW,43.0,N,NW,4.0,...,31,1025.7,1022.2,1,7,12.7,23.7,No,0.0,No
353,8.3,28.5,0.0,5.8,9.8,NW,46.0,W,NW,2.0,...,30,1024.1,1019.8,1,6,16.8,27.4,No,0.2,No
354,11.3,27.4,0.2,7.6,12.1,NW,52.0,SE,NW,6.0,...,20,1021.4,1017.5,1,1,16.4,26.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# 10) Find all the instances when "WindSpeed9am is above 7.0" and "Temp9am is 14"?

In [119]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [120]:
data["WindSpeed9am"]

0       6.0
1       4.0
2       6.0
3      30.0
4      20.0
       ...
361     7.0
362     2.0
363    11.0
364     6.0
365    31.0
Name: WindSpeed9am, Length: 366, dtype: float64

In [121]:
data["WindSpeed9am"] > 7.0

0      False
1      False
2      False
3       True
4       True
       ...
361    False
362    False
363     True
364    False
365     True
Name: WindSpeed9am, Length: 366, dtype: bool

In [122]:
data[data["WindSpeed9am"] > 7.0]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,9.0,20.6,0.0,9.0,6.2,ENE,39.0,S,SW,11.0,...,28,1022.3,1018.6,7,5,11.4,18.5,No,0.8,No
356,3.4,15.0,0.8,4.8,11.7,S,70.0,S,S,35.0,...,24,1023.4,1023.1,1,5,8.3,14.3,No,0.0,No
357,3.2,18.0,0.0,7.4,12.2,SSE,48.0,SSE,S,26.0,...,25,1026.6,1022.8,1,2,9.1,16.3,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [127]:
data["Temp9am"] == 14

0      False
1      False
2      False
3      False
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: Temp9am, Length: 366, dtype: bool

In [128]:
data[data["Temp9am"] == 14]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
22,12.8,18.5,25.8,2.8,0.6,ESE,28.0,S,SE,13.0,...,79,1024,1014.9,8,8,14.0,16.8,Yes,0.4,No
101,9.1,23.1,0.0,5.8,9.6,ENE,41.0,SSE,W,17.0,...,37,1024,1011.4,1,7,14.0,21.4,No,0.0,No
128,9.5,27.4,3.0,4.8,11.5,NNW,24.0,SSE,NNW,6.0,...,39,1024,1020.7,1,7,14.0,24.9,Yes,0.0,No
142,11.6,19.6,0.0,2.8,1.6,E,33.0,SE,ESE,6.0,...,64,1024,1021.8,7,8,14.0,17.9,No,0.0,No
161,7.2,22.9,0.0,2.2,9.5,E,26.0,NNW,N,4.0,...,28,1024,1019.2,1,1,14.0,22.2,No,0.0,No
169,7.9,19.7,0.0,3.2,8.3,ESE,48.0,SSE,ENE,17.0,...,43,1024,1024.1,3,6,14.0,19.1,No,0.0,No

In [131]:
data[(data["WindSpeed9am"] > 7.0) & (data["Temp9am"] == 14)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
22,12.8,18.5,25.8,2.8,0.6,ESE,28.0,S,SE,13.0,...,79,1024,1014.9,8,8,14.0,16.8,Yes,0.4,No
101,9.1,23.1,0.0,5.8,9.6,ENE,41.0,SSE,W,17.0,...,37,1024,1011.4,1,7,14.0,21.4,No,0.0,No
169,7.9,19.7,0.0,3.2,8.3,ESE,48.0,SSE,ENE,17.0,...,43,1024,1024.1,3,6,14.0,19.1,No,0.0,No

# 11) What is the mean value of each column against each "RainTomorrow"?

In [132]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1024,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [133]:
data.groupby("RainTomorrow").mean()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
RainTomorrow,,,,,,,,,,,,,,,,,
No,6.607333,20.396000,1.164000,4.408667,8.540604,38.308725,9.319728,17.810000,70.896667,41.623333,1024.0,1017.932333,3.496667,3.540000,11.878000,19.196333,0.056667
Yes,10.257576,21.251515,2.630303,5.036364,5.015385,46.757576,11.153846,18.787879,77.212121,57.681818,1024.0,1011.710606,5.681818,6.227273,14.542424,19.387879,7.663636

# 12) What is the minimum and maximum value of each column against "RainTomorrow"?

In [134]:
data.groupby("RainTomorrow").min()

/var/folders/5f/zvvxs6012zn4htwxbbkh2mvh0000gn/T/ipykernel_3299/2902472375.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.min is deprecated. In a future version, a TypeError will be raised. Before calling .min, select only columns which should be valid for the function.
  data.groupby("RainTomorrow").min()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM
RainTomorrow,,,,,,,,,,,,,,,,,,
No,-5.3,7.6,0.0,0.2,0.0,13.0,0.0,2,36,13,1024,997.5,0,0,0.1,5.1,No,0.0
Yes,-2.3,8.7,0.0,0.6,0.0,17.0,0.0,0,44,22,1024,996.8,0,1,1.0,5.7,No,1.2

In [135]:
data.groupby("RainTomorrow").max()

/var/folders/5f/zvvxs6012zn4htwxbbkh2mvh0000gn/T/ipykernel_3299/2813169628.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  data.groupby("RainTomorrow").max()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM
RainTomorrow,,,,,,,,,,,,,,,,,,
No,17.9,35.8,25.8,12.6,13.6,78.0,35.0,50,99,86,1024,1033.2,8,8,24.7,34.5,Yes,1.0
Yes,20.9,35.7,39.8,13.8,12.1,98.0,41.0,52,99,96,1024,1027.9,8,8,24.5,34.0,Yes,39.8

# 13) Show all the records where "RainTomorrow" is "Yes"

In [136]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1024,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [137]:
data["RainTomorrow"] == "Yes"

0       True
1       True
2       True
3       True
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: RainTomorrow, Length: 366, dtype: bool

In [138]:
data[data["RainTomorrow"] == "Yes"]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1024,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1024,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1024,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1024,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1024,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1024,1016.0,4,7,16.3,23.2,No,13.2,Yes

In [139]:
data.groupby("RainTomorrow").get_group("Yes")

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1024,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1024,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1024,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1024,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1024,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1024,1016.0,4,7,16.3,23.2,No,13.2,Yes

# 14) Find all the instances when "RainTomorrow is Yes" or "Rainfall is above 35"

In [140]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1024,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [142]:
data["RainTomorrow"] == "Yes"

0       True
1       True
2       True
3       True
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: RainTomorrow, Length: 366, dtype: bool

In [143]:
data[data["RainTomorrow"] == "Yes"]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1024,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1024,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1024,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1024,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1024,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1024,1016.0,4,7,16.3,23.2,No,13.2,Yes

In [144]:
data["Rainfall"] > 35

0      False
1      False
2      False
3       True
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: Rainfall, Length: 366, dtype: bool

In [145]:
data[data["Rainfall"] > 35]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes

In [148]:
data[(data["RainTomorrow"] == "Yes") | (data["Rainfall"] > 35)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1024,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1024,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1024,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1024,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1024,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1024,1016.0,4,7,16.3,23.2,No,13.2,Yes

# 15) 14) Find all the instances when "RainTomorrow is No" or "Rainfall is below 35

In [149]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1024,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1024,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [150]:
data[(data["RainTomorrow"] == "No") | (data["Rainfall"] < 35)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,WeatherConditionToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1024,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1024,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1024,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1024,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1024,1021.7,7,5,10.9,14.8,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1024,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1024,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1024,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1024,1009.2,1,1,23.8,28.6,No,0.0,No